[build]
  publish = "."

# Newsletter success
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

# Waitlist success
[[redirects]]
  from = "/waitlist-success"
  to = "/waitlist-success.html"
  status = 200
