[build]
  publish = "."

# Newsletter success
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

# Waitlist success (Free)
[[redirects]]
  from = "/waitlist-success"
  to = "/waitlist-success.html"
  status = 200

# Pro Waitlist success
[[redirects]]
  from = "/pro-waitlist-success"
  to = "/pro-waitlist-success.html"
  status = 200
